---
title: "2025 Big Ten Baseball Standings Predictor"
author: "kylegilber"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    latex_engine: lualatex
---

```{r Imports, warning=FALSE, echo=FALSE}

# Import packages
library(dplyr)
library(tidyr)
library(purrr)
library(kableExtra)
library(knitr)
library(tinytex)
library(stats)
library(stringr)
library(betareg)
library(pROC)
library(lubridate)
library(caret)
library(glue)

# Load data
files <- list.files("~/Github/big-ten-baseball-model/data/", full.names = TRUE)
invisible(lapply(files, load, envir = .GlobalEnv))
```

```{r Globals, echo=FALSE}

# List teams in the big ten conference
bigten.teams <- c("ILL_ILL", "IU", "IOW_HAW", "MAR_TER", "MIC_SPA", "MIC_WOL", 
  "MIN_GOL", "NEB", "NOR_CAT", "OSU_BUC", "PEN_NIT", "PUR_BOI", "RUT_SCA")

# Specify factors for frequency analysis
factors <- list("PlayResult", "KorBB", "PitchCall", "RunsScored")

# Specify grouping variables
variables <- c("GameID", "HomeTeam", "AwayTeam", "Date")

# Specify predictor variable types
pred.vars <- c("FIP", "WHIP", "wOBA", "ISO", "K9", "BB9")
```


```{r Data Cleaning, warning=FALSE, echo=FALSE}

# Loop through global environment
for (name in ls()) {
  
  # Get environment objects
  object <- get(name)
  
  # Get data frame objects
  if (is.data.frame(object) & grepl(paste(bigten.teams, collapse = "|"), name)) {
    
    # Remove "undefined" factor level
    levels(object$PlayResult)[levels(object$PlayResult) == "Undefined"] <- NA
    levels(object$KorBB)[levels(object$KorBB) == "Undefined"] <- NA
    
    # Filter in-conference game data
    temp <- subset(object, HomeTeam %in% bigten.teams & AwayTeam %in% bigten.teams)
    assign(name, temp)
  }
}

# Remove temporary variables
rm(name, files, temp, object)
```

```{r Transformation Function, echo=FALSE}

# Define frequency analysis function
freq <- function(data, type) {
  map(factors, ~ data %>% 
    count(GameID, {{type}}, .data[[.x]]) %>% 
    pivot_wider(
      names_from = .data[[.x]],
      values_from = n,
      values_fill = 0
    )
  )
}

# Define function to summarize team data
summarize.team <- function(data) {
  
  # Frequency analysis for factors
  pitcher.counts <- freq(data, Pitcher)
  batter.counts <- freq(data, Batter)
  
  # Derive innings-pitched pitcher statistic
  IP <- data %>% distinct(!!!syms(variables), Inning, Pitcher, PitcherTeam) %>% 
    count(!!!syms(variables), Date, Pitcher, PitcherTeam, name = "IP")
  
  # Derive plate appearances batting statistic
  PA <- data %>% distinct(!!!syms(variables), Inning, PAofInning, Batter, BatterTeam) %>%
    count(!!!syms(variables), Date, Batter, BatterTeam, name = "PA")
  
  # Specify variables to join by
  keys <- c("GameID", "Pitcher")
  
  # Join pitcher counts and innings pitched
  pitcher.data <- left_join(IP, reduce(pitcher.counts, left_join, by = keys), by = keys) %>% 
    mutate(
      
      # Fielding independent pitching (FIP)
      FIP = (13*HomeRun + 3*(Walk + HitByPitch) - 2*Strikeout) / IP + 4.22,
      
      # Strikeouts & walks per nine innings (K/9, BB/9)
      K9 = (Strikeout / IP) * 9, BB9 = (Walk / IP) * 9,
      
      # Walks & hits per inning pitched
      WHIP = (Walk + Single + Double + 
        tryCatch({Triple}, error = function(cond) {0}) + HomeRun) / IP
      
    ) %>% 
    
    # Summarize across both teams
    reframe(
      Date = Date,
      HomeTeam = HomeTeam,
      AwayTeam = AwayTeam,
      across(
        c(FIP, K9, BB9, WHIP),
        ~mean(.x[PitcherTeam == HomeTeam]),
        .names = "Home_{.col}"),
      across(
        c(FIP, K9, BB9, WHIP),
        ~mean(.x[PitcherTeam == AwayTeam]),
        .names = "Away_{.col}"),
      .by = GameID
    )
  
  # Update keys for batter data
  keys <- c("GameID", "Batter")
  
  # Join batter counts and plate appearances
  batter.data <- left_join(PA, reduce(batter.counts, left_join, by = keys), by = keys) %>% 
    mutate(
      
      # Weighted on-base average (wOBA)
      wOBA = (0.812*Walk + 0.838*HitByPitch + 0.943*Single + 1.245*Double + 
        1.537*tryCatch({Triple}, error = function(cond) {0}) + 1.764*HomeRun) 
        / (PA + Walk + Sacrifice + HitByPitch),
      
      # Strikeout & walk percentage (K%, BB%)
      `K%` = Strikeout / PA, `BB%` = Walk / PA,
      
      # Isolated power (ISO)
      ISO = (Double + 2 * tryCatch({Triple}, error = function(cond) {0}) + 
        3 * HomeRun) / PA
      
    ) %>% 

    # Summarize across both teams
    reframe(
      Date = Date,
      HomeTeam = HomeTeam,
      AwayTeam = AwayTeam,
      across(
        c(wOBA, `K%`, `BB%`, ISO),
        ~mean(.x[BatterTeam == HomeTeam]),
        .names = "Home_{.col}"),
      across(
        c(wOBA, `K%`, `BB%`, ISO),
        ~mean(.x[BatterTeam == AwayTeam]),
        .names = "Away_{.col}"),
      .by = GameID
    )
  
  # Join batter and pitcher summary data
  pitcher.data %>% left_join(batter.data, by = "GameID") %>% distinct() %>% select(-GameID)
}
```

```{r Data Transformation, warning=FALSE, echo=FALSE}

# Summarize each team's in-conference game data
bigten.team.data <- lapply(bigten.teams, function(team) {summarize.team(get(team))})

# Merge in-conference game data for all teams
bigten.games <- Reduce(rbind, bigten.team.data) %>% 
  mutate(
    Date = coalesce(Date.x, Date.y),
    HomeTeam = coalesce(HomeTeam.x, HomeTeam.y),
    AwayTeam = coalesce(AwayTeam.x, AwayTeam.y)
  ) %>% 
  select(-Date.x, -Date.y, -HomeTeam.x, -HomeTeam.y, -AwayTeam.x, -AwayTeam.y) %>% 
  distinct()

# Remove incorrectly-dated game
bigten.games <- bigten.games[-61, ]

# Create 'result' column to store game result
# Result stores 1 if the home team wins, otherwise 0
bigten.games$Result <- c(0,0,1,0,1,1,1,1,1,0,1,1,1,0,1,1,0,1,1,1,0,1,0,0,0,1,0,
  1,1,0,1,0,1,1,1,1,0,0,0,1,1,0,1,1,0,0,0,1,1,1,0,0,1,0,1,1,1,1,1,1,0,1,1,1,0,1,
  0,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,0,0,
  1,0,1,1,0,1,0,1,1,1,0,0,0,0,1,1,0,0,0,1,1,0,1,0,1,1,1,1,0,0,1,1,0,1,1,0,0,0,1,
  1,0,1,0,0,0)
```

```{r Univariate Analysis, echo=FALSE}

# Define plot parameters
par(mfrow = c(2,3))

# Visualize predictor variables
for (var in pred.vars) {
  
  # Combine home and away statistic values
  data <- unlist(bigten.games[,grep(var, names(bigten.games), value = TRUE)])
  
  # Create a histogram from the data
  hist(data, main = paste("Histogram of", var), xlab = paste(var, "values"))
}

```


```{r Table 1}
#| warning: false
#| message: false
#| echo: false

vars <- data.frame(
  
  # Variable names
  Variable = c(
    "Result", "Home.FIP", "Away.FIP", "Home.WHIP", "Away.WHIP", "Home.K9",
    "Away.K9", "Home.BB9", "Away.BB9", "Home.wOBA", "Away.wOBA", "Home.ISO",
    "Away.ISO", "Home.K%", "Away.K%", "Home.BB%", "Away.BB%"
  ),
  
  # Variable type in the model
  Type = c("Response", rep("Predictor", 16)),
  
  # An explanation of the variable
  Explanation = c(
    "An indicator variable representing whether the home team (1) or the away team (0) won the game",
    "Home team Fielding Independent Pitching (FIP) pitching statistic from the game",
    "Away team Fielding Independent Pitching (FIP) pitching statistic from the game",
    "Home team Walks + Hits per Inning Pitched (WHIP) pitching statistic from the game",
    "Away team Walks + Hits per Inning Pitched (WHIP) pitching statistic from the game",
    "Home team pitcher Strikeouts per Nine Innings (K9) rate from the game",
    "Away team pitcher Strikeouts per Nine Innings (K9) rate from the game",
    "Home team pitcher Walks per Nine Innings (BB9) rate from the game",
    "Away team pitcher Walks per Nine Innings (BB9) rate from the game",
    "Home team Weighted On-Base Average (wOBA) batting statistic from the game",
    "Away team Weighted On-Base Average (wOBA) batting statistic from the game",
    "Home team Isolated Power (ISO) batting statistic from the game",
    "Away team Isolated Power (ISO) batting statistic from the game",
    "Home team batter Strikeout Percentage (K%) from the game",
    "Away team batter Strikeout Percentage (K%) from the game",
    "Home team batter Walk Percentage (BB%) from the game",
    "Away team batter Walk Percentage (BB%) from the game"
  ),
  
  # Range of values for each variable
  Value = c(
    glue("0: {round(sum(bigten.games$Result) / nrow(bigten.games),2)*100}% 
    1: {round(1 - (sum(bigten.games$Result) / nrow(bigten.games)),2)*100}%"),
    glue("{round(min(bigten.games$Home_FIP), 2)} ~ 
      {round(max(bigten.games$Home_FIP), 2)}"),
    glue("{round(min(bigten.games$Away_FIP), 2)} ~ 
      {round(max(bigten.games$Away_FIP), 2)}"),
    glue("{round(min(bigten.games$Home_WHIP), 2)} ~ 
      {round(max(bigten.games$Home_WHIP), 2)}"),
    glue("{round(min(bigten.games$Away_WHIP), 2)} ~ 
      {round(max(bigten.games$Away_WHIP), 2)}"),
    glue("{round(min(bigten.games$Home_K9), 2)} ~ 
      {round(max(bigten.games$Home_K9), 2)}"),
    glue("{round(min(bigten.games$Away_K9), 2)} ~ 
      {round(max(bigten.games$Away_K9), 2)}"),
    glue("{round(min(bigten.games$Home_BB9), 2)} ~ 
      {round(max(bigten.games$Home_BB9), 2)}"),
    glue("{round(min(bigten.games$Away_BB9), 2)} ~ 
      {round(max(bigten.games$Away_BB9), 2)}"),
    glue("{round(min(bigten.games$Home_wOBA), 2)} ~ 
      {round(max(bigten.games$Home_wOBA), 2)}"),
    glue("{round(min(bigten.games$Away_wOBA), 2)} ~ 
      {round(max(bigten.games$Away_wOBA), 2)}"),
    glue("{round(min(bigten.games$Home_ISO), 2)} ~ 
      {round(max(bigten.games$Home_ISO), 2)}"),
    glue("{round(min(bigten.games$Away_ISO), 2)} ~ 
      {round(max(bigten.games$Away_ISO), 2)}"),
    glue("{round(min(bigten.games$`Home_K%`), 2)} ~ 
      {round(max(bigten.games$`Home_K%`), 2)}"),
    glue("{round(min(bigten.games$`Away_K%`), 2)} ~ 
      {round(max(bigten.games$`Away_K%`), 2)}"),
    glue("{round(min(bigten.games$`Home_BB%`), 2)} ~ 
      {round(max(bigten.games$`Home_BB%`), 2)}"),
    glue("{round(min(bigten.games$`Away_BB%`), 2)} ~ 
      {round(max(bigten.games$`Away_BB%`), 2)}")
  )
)

vars %>% 
  knitr::kable(
    caption = "Variables used in the analysis",
    align = "l",
  ) %>% 
  kableExtra::kable_styling(
    position = "center",
    bootstrap_options = c("striped")
  ) %>% 
  kable_classic(
    html_font = "Cambria",
    full_width = FALSE
  ) %>% 
  column_spec(3, width = "8cm")
```

```{r Modeling, echo=FALSE}

# Set seed for reproducibility
set.seed(123)

# Perform 70/30 train-test split
indices <- sample(nrow(bigten.games), size = 0.7 * nrow(bigten.games))
train <- bigten.games[indices,]
test <- bigten.games[-indices,]

# Define model predictors
model.formula <- formula(Result ~ Home_FIP + Away_FIP + Home_WHIP + Away_WHIP + 
  Home_K9 + Away_K9 + Home_BB9 + Away_BB9 + Home_wOBA + Away_wOBA + Home_ISO + 
  Away_ISO + `Home_K%` + `Away_K%` + `Home_BB%` + `Away_BB%`)

# Multiple linear regression model
linear.model <- lm(model.formula, data = train)

# Factorize 'result' response variable
train$Result <- factor(train$Result)

# Logistic regression model
logistic.model <- glm(model.formula, family = binomial, data = train)

# Predict test results
linear.pred <- predict(linear.model, test[,1:16], type = "response") %>% round(0)
logistic.pred <- predict(logistic.model, test[,1:16], type = "response") %>% round(0)

# Create confusion matrices
linear.conf <- confusionMatrix(as.factor(linear.pred), as.factor(test$Result))
logistic.conf <- confusionMatrix(as.factor(logistic.pred), as.factor(test$Result))

linear.conf$overall["Accuracy"]
logistic.conf$overall["Accuracy"]






# Train beta regression model
beta.model <- betareg(
  `Win%` ~ FIP_mean + K9_mean + BB9_mean + WHIP_mean + wOBA_mean + `K%_mean` + 
  `BB%_mean` + ISO_mean + RBI + RA, data = train
)

# Make predictions on test data
logistic.pred <- predict(logistic.model, newdata = test, type = "response")
beta.pred <- predict(beta.model, newdata = test, type = "response")

# Plot histogram of predictions
hist(logistic.pred, main = "Histogram of Predicted Win %", xlab = "Logistic Predictions")
hist(beta.pred, main = "Histogram of Predicted Win %", xlab = "Beta Predictions")

# Root mean squared error (RMSE)
beta.RMSE <- sqrt(mean((test$`Win%` - beta.pred)^2))

# Mean absolute error (MAE)
beta.MAE <- mean(abs(test$`Win%` - beta.pred))

# Pseudo R squared
summary(beta.model$pseudo.r.squared)

test$`Win%`
logistic.pred

rm(indices, size, train, vars, model, i)
rm(test, logistic.model, logistic.pred)
```
```{r Table 2}

model.summary <- data.frame(
  Model = c("Linear Regression", "Logistic Regression"),
  
)
```

